### ISSUE TITLE
prebuilt binary for win32 nwjs version v86 not working

### ISSUE THREAD

**Issue by danielklug** [ElectronForConstruct/greenworks-prebuilds#167] opened 2020-10-09 07:16 UTC
When using _ugcGetUserItems the successCallback returns an array of items, unfortunately with wrong values.

The fields file, previewFile, publishedFileId, and steamIDOwner are having the same values.
e.g:
[wrongRetValues.txt](https://github.com/ElectronForConstruct/greenworks-prebuilds/files/5353469/wrongRetValues.txt)

I built the binary myself with no code changes and then it works.
correct values:
[correctRetValues.txt](https://github.com/ElectronForConstruct/greenworks-prebuilds/files/5353080/correctRetValues.txt)

With the wrong values there is no way to be able to update WorkShop Items.

**To Reproduce**
1. Publish a workshop file with (_publishWorkshopFile)
2. Retrieve the values with _ugcGetUserItems

**Additional context**
Attached the prebuilt node from today and my own just to make reproducing easier.
[greenworks_nodes.zip](https://github.com/ElectronForConstruct/greenworks-prebuilds/files/5353113/greenworks_nodes.zip)

So I guess the build is broken, haven tested other os versions yet, but I will test osx soon.

**Comment by Armaldio** [comment] 2020-10-09 07:34
What SDK version did you build against ?
May be a mismatch between the version you are using and the version we use to make the prebuilds (**Steam SDK 1.42**)

**Comment by danielklug** [comment] 2020-10-09 07:34
I've tested osx64 prebuild version and that works :) .

**Comment by Armaldio** [comment] 2020-10-09 07:35
Oh, so that must be a windows issue then

**Comment by danielklug** [comment] 2020-10-09 07:43
I've built against Steam SDK v1.46

**Comment by Armaldio** [comment] 2020-10-09 08:10
That must be that then
Will try to update internal SDK to 1.46

**Comment by Armaldio** [comment] 2020-12-01 07:32
Any update on this ?
Will close otherwise

**Comment by danielklug** [comment] 2020-12-01 07:51
Sorry I forgot to comment here but it's not solved the reason was that greenworks string to uint64 conversion didn't work so I built it myself and created a pull request there: [https://github.com/greenheartgames/greenworks/pull/281](url)

**Comment by Armaldio** [comment] 2020-12-01 08:11
Thanks for the very quick reply!
Since the issue is not directly related to this projet, I will close this issue. Feel free to reopen one once your PR is merged but the automated builds still don't work.

**Closed by Armaldio** 2020-12-01 08:11 UTC
Labels: bug, dependencies, enhancement, need-answer
