### ISSUE TITLE
Downloading any bundle seems to fail

### ISSUE THREAD

**Issue by Morthy** [ElectronForConstruct/greenworks-prebuilds#565] opened 2023-05-31 04:29 UTC
**Describe the bug**
Downloading any bundle does nothing. The browser console shows a 502 response with the following error:

![image](https://github.com/ElectronForConstruct/greenworks-prebuilds/assets/5537959/983db9ef-6c1b-4098-a284-29a405b29de0)

**To Reproduce**
1. Select and download any bundle

**Comment by Armaldio** [comment] 2023-05-31 07:06
Hey, 

Can you please try to log out and in ?

Seems a duplicate of https://github.com/ElectronForConstruct/greenworks-prebuilds/issues/337 (https://github.com/ElectronForConstruct/greenworks-prebuilds/issues/337#issuecomment-870761638)

**Comment by Morthy** [comment] 2023-05-31 14:22
Oh, actually it worked for one download, and then I got a 502 again. Logging out and in again fixed it, but then it broke again, and now logging out and in again doesn't fix it. But I managed to get the files I need :)

**Comment by Armaldio** [comment] 2023-06-01 10:53
That's weird indeed
I can't manage to reproduce

**Comment by Armaldio** [comment] 2023-07-17 08:36
Fixed by https://github.com/ElectronForConstruct/greenworks-prebuilds-website/commit/077ebab5d9745e04aed03280f388b606b4280a64

**Closed by Armaldio** 2023-07-17 08:36 UTC
Labels: bug, website
